# Generated by Django 5.1.4 on 2024-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_created_at_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
